[build]
  # Only run the sed command, as you have no npm build process
  command = "sed -i \"s#YOUR_MAPBOX_ACCESS_TOKEN#$MAPBOX_TOKEN#g\" assets/js/wawasanverse.js"
  publish = "."

[functions]
  directory = "netlify/functions"
